version: '3.8'

services:
  api:
    build: .
    container_name: 3sila-ai-api
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - 3sila-network

networks:
  3sila-network:
    driver: bridge